name: speech-rec-env

channels:
        - defaults
        - conda-forge

dependencies:
        - python=3.7
        - tensorflow=2.0
        - pandas
        - opencv
        - dlib
        - matplotlib=2.0.2
        - jupyterlab
        - scikit-image
        - tqdm
